config/routes.rb
Rails.application.routes.draw do
  resources :jobs, only: [:index, :show]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'jobs#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/job.rb
class Job < ActiveRecord::Base
  geocoded_by :full_street_address
  after_validation :geocode
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_job.html.slim
= link_to job, data: {lat: job.latitude, lon: job.longitude, marker: job.notes }, class: 'list-group-item' do
  h4.list-group-item-heading
    = image_tag 'construction.png', class: 'pull-left'
    = job.full_street_address
  p.list-group-item-text= simple_format job.notes

app/views/jobs/index.html.slim
h1 Jobmap

.row
  .col-md-9#mapholder
  .col-md-3
    #markers.list-group= render @jobs

app/views/jobs/show.html.slim
.panel.panel-primary
  .panel-heading= @job.full_street_address
  .panel-body= simple_format @job.notes
  .panel-footer
    .btn.btn-primary Check In
    = link_to 'Back', jobs_path, class: 'btn btn-default'

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      | jobmap
      = " | #{yield(:title)}" if content_for?(:title)
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Jobmap'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == javascript_include_tag "http://maps.google.com/maps/api/js?key=#{Rails.application.secrets.google_maps_key}&sensor=true"
    = yield :head
    == csrf_meta_tags
  body
    header= render 'layouts/navigation'
    .container
      .row
        .col-md-12
          = bootstrap_flash
          = yield

app/views/pages/home.html.slim
.jumbotron
  h1 Jobmap

#mapholder style='height: 40em'

- if Job.any?
  h4 Jobs listing (TODO map markers)
  ul
    - Job.all.each do |job|
      li= job.full_street_address